# -*- coding: utf-8 -*-
"""student performance analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hAF8riXVR8s-9UaVKW7k_YeqHsOIl_ey

# Student Performance Analysis Project

This project analyzes student academic and lifestyle factors and predicts exam scores using Machine Learning.
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from google.colab import files
import pandas as pd

# Upload dataset
uploaded = files.upload()

# Get the uploaded file name automatically
filename = list(uploaded.keys())[0]

# Load dataset
df = pd.read_csv(filename)

# Show first 5 rows
df.head()

df.head()

df.columns

df.info()

df.isnull().sum()

df.duplicated().sum()

df.dtypes

df.describe()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()

df.columns

X = df.drop(["Student_ID", "Exam_Score", "Passed"], axis=1)

y = df["Exam_Score"]

X.head()

y.head()

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.linear_model import LinearRegression

X.dtypes

X = pd.get_dummies(X, columns=["Stress_Level"], drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

y_pred[:5]

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

plt.figure(figsize=(8,5))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Exam Score")
plt.ylabel("Predicted Exam Score")

plt.title("Actual vs Predicted Exam Scores")

plt.show()

prediction = model.predict(X_test.iloc[[0]])

print("Predicted Exam Score:", prediction[0])
print("Actual Exam Score:", y_test.iloc[0])

import pickle

with open("student_performance_model.pkl", "wb") as file:
    pickle.dump(model, file)

plt.figure(figsize=(8,5))

sns.scatterplot(
    x="Study_Hours_Per_Day",
    y="Exam_Score",
    data=df
)

plt.title("Study Hours vs Exam Score")
plt.xlabel("Study Hours Per Day")
plt.ylabel("Exam Score")

plt.show()

## Model Evaluation - RMSE

import numpy as np

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("RMSE:", rmse)

## Student Performance Prediction System

df["Stress_Level"].unique()

try:

    study_hours = float(input("Enter study hours per day: "))
    attendance = float(input("Enter attendance percentage: "))
    sleep_hours = float(input("Enter sleep hours per day: "))
    extra_hours = float(input("Enter extracurricular hours per week: "))
    stress = input("Enter stress level (Low/Medium/High): ")


    new_student = pd.DataFrame({
    "Study_Hours_Per_Day": [study_hours],
    "Attendance_Rate_Percentage": [attendance],
    "Sleep_Hours_Per_Day": [sleep_hours],
    "Extracurricular_Hours_Per_Week": [extra_hours],
    "Stress_Level_Low": [1 if stress.lower() == "low" else 0],
    "Stress_Level_Moderate": [1 if stress.lower() == "moderate" else 0]
})

    prediction = model.predict(new_student)

    print("Predicted Exam Score:", prediction[0])


except Exception as e:
    print("Error:", e)

X.columns

study_hours = float(input("Enter study hours per day: "))
attendance = float(input("Enter attendance percentage: "))
sleep_hours = float(input("Enter sleep hours per day: "))
extra_hours = float(input("Enter extracurricular hours per week: "))
stress = input("Enter stress level (Low/Medium/High): ")


new_student = pd.DataFrame({
    "Study_Hours_Per_Day": [study_hours],
    "Attendance_Rate_Percentage": [attendance],
    "Sleep_Hours_Per_Day": [sleep_hours],
    "Extracurricular_Hours_Per_Week": [extra_hours],
    "Stress_Level_Low": [1 if stress == "Low" else 0],
    "Stress_Level_Moderate": [1 if stress == "Moderate" else 0] # Corrected from Stress_Level_Medium
})
prediction = model.predict(new_student)

print("Predicted Exam Score:", prediction[0])

print(df.columns)

df['Extracurricular_Hours_Per_Week'].describe()

import matplotlib.pyplot as plt
import seaborn as sns

# Create activity participation column
df['Participates_In_Activities'] = df['Extracurricular_Hours_Per_Week'].apply(
    lambda x: 'Yes' if x > 0 else 'No'
)

# Create bar chart
plt.figure(figsize=(6,4))
sns.barplot(
    data=df,
    x='Participates_In_Activities',
    y='Exam_Score'
)

plt.title('Exam Score Comparison: Activities vs Non-Participants')
plt.xlabel('Participates in Activities')
plt.ylabel('Average Exam Score')
plt.show()